### ISSUE TITLE
'NoneType' object has no attribute 'getVertices'

### ISSUE THREAD

**Issue by aoshiro10** [aoshiro10/graph-coloring-optimization#11]
I missed this on the lastest pull request.

When I run the command `python3 main.py`, I get the following error:
**`'NoneType'` object has no attribute `'getVertices'`**

`line 10, in convertToNX G.add_nodes_from(graph.getVertices())`

**Comment by DavidLBick** [comment]
Oh just have to move line 20 of main.py to be after the following line

**Comment by DavidLBick** [comment]
Do you have to make a pull request for that or can just move that

**Comment by aoshiro10** [comment]
You can just fix and merge to master.

**Comment by DavidLBick** [comment]
What branch is this on

**Comment by DavidLBick** [comment]
Or directly push it to master

**Comment by aoshiro10** [comment]
Yeah just push to master. You probably shouldn't do this, but it's fine here.

**Comment by aoshiro10** [comment]
Make a new pull request.
